config/routes.rb
Rails.application.routes.draw do
  #resources :eno_cards

  root to: "eno_cards#show_random"

  get '/cards', to: 'eno_cards#index'
  get '/counts', to: 'eno_cards#counts'
  get 'loaderio-:id' => 'loaderio#verify'
  get '/:id', to: 'eno_cards#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eno_card.rb
class EnoCard < ApplicationRecord
  is_impressionable counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eno_cards_controller.rb
class EnoCardsController < ApplicationController
  before_action :set_eno_card, only: [:show, :edit, :update, :destroy]

  # GET /eno_cards
  # GET /eno_cards.json
  def index
    @eno_cards = EnoCard.order(:text).all
  end

  # GET /eno_cards/1
  # GET /eno_cards/1.json
  def show

  end

  def verify
    @eno_cards = EnoCard.order(impressions_count: :desc).where('impressions_count > 0')
    #binding.pry
  end


  def counts
    @eno_cards = EnoCard.order(impressions_count: :desc, text: :asc).where('impressions_count > 0')
    #binding.pry
  end

  def show_random
    @eno_card = EnoCard.where(impressions_count: EnoCard.order(impressions_count: :asc).first.impressions_count).sort_by{rand}.slice(0,1).first
    impressionist(@eno_card)
  end

  # GET /eno_cards/new
  def new
    @eno_card = EnoCard.new
  end

  # GET /eno_cards/1/edit
  def edit
  end

  # POST /eno_cards
  # POST /eno_cards.json
  def create
    @eno_card = EnoCard.new(eno_card_params)

    respond_to do |format|
      if @eno_card.save
        format.html { redirect_to @eno_card, notice: 'Eno card was successfully created.' }
        format.json { render :show, status: :created, location: @eno_card }
      else
        format.html { render :new }
        format.json { render json: @eno_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eno_cards/1
  # PATCH/PUT /eno_cards/1.json
  def update
    respond_to do |format|
      if @eno_card.update(eno_card_params)
        format.html { redirect_to @eno_card, notice: 'Eno card was successfully updated.' }
        format.json { render :show, status: :ok, location: @eno_card }
      else
        format.html { render :edit }
        format.json { render json: @eno_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eno_cards/1
  # DELETE /eno_cards/1.json
  def destroy
    @eno_card.destroy
    respond_to do |format|
      format.html { redirect_to eno_cards_url, notice: 'Eno card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_eno_card
    @eno_card = EnoCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def eno_card_params
    params.require(:eno_card).permit(:text)
  end
end

app/controllers/loaderio_controller.rb
# app/controllers/loaderio_controller.rb
class LoaderioController < ActionController::Base
  def verify
    send_data token, :type => "text/plain",
      :disposition => "inline"
  end

  private

  def token
    "loaderio-a6c8a368ec0ac4c24c199b8d6cf9aca1"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/eno_cards_helper.rb
module EnoCardsHelper
end

app/views/card/show_random.erb
<script type="text/javascript">

	
    setInterval(function() {
      window.location.reload();
    }, 300000); 

    $( document ).ready(function() {
	document.onclick=function() { location.reload(); };
	document.ontouch=function() { location.reload(); };
	$('#wrapper').click(function() {
		location.reload();
	});
	    
    	$('#content').textfill({
        maxFontPixels: 100,
        changeLineHeight: true
    });
    	});
</script>

<div id="wrapper" style="width:100hh;height:75vh;-webkit-border-radius: 20px;-moz-border-radius: 20px;border-radius: 20px;border:5px solid #000000;background:rgba(226,227,193,0.5);-webkit-box-shadow: #B3B3B3 9px 9px 9px;-moz-box-shadow: #B3B3B3 9px 9px 9px; box-shadow: #B3B3B3 9px 9px 9px;padding: 15px;text-align: center;vertical-align: middle;">

<div id="content" style="position: relative;top: 50%;transform: translateY(-50%); ">
<span>
<%= @card.text %>
</span>
</div>
</div>

app/views/eno_cards/_form.html.erb
<%= form_for(eno_card) do |f| %>
  <% if eno_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(eno_card.errors.count, "error") %> prohibited this eno_card from being saved:</h2>

      <ul>
      <% eno_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eno_cards/counts.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead style="display: none;">
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @eno_cards.each do |eno_card| %>
      <tr>
        <td><%= strip_tags eno_card.text %></td>
        <td><%= eno_card.impressions_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/eno_cards/edit.html.erb
<h1>Editing Eno Card</h1>

<%= render 'form', eno_card: @eno_card %>

<%= link_to 'Show', @eno_card %> |
<%= link_to 'Back', eno_cards_path %>

app/views/eno_cards/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead style="display: none;">
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @eno_cards.each do |eno_card| %>
      <tr>
        <td><a href="/<%= eno_card.id %>"><%= strip_tags eno_card.text %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/eno_cards/new.html.erb
<h1>New Eno Card</h1>

<%= render 'form', eno_card: @eno_card %>

<%= link_to 'Back', eno_cards_path %>

app/views/eno_cards/show.html.erb
<script type="text/javascript">

            $(document).ready(function() {
                // document.onclick = function() {
                //     location.reload();
                // };
                // document.ontouch = function() {
                //     location.reload();
                // };
                $('#wrapper').click(function() {
                    location.reload();
                });
                $('#content').textfill({
                    maxFontPixels: 100,
                    changeLineHeight: true
                });
            });

</script>
<div id="wrapper" style="width:100hh;height:75vh;-webkit-border-radius: 20px;-moz-border-radius: 20px;border-radius: 20px;border:5px solid #000000;background:rgba(226,227,193,0.5);-webkit-box-shadow: #B3B3B3 9px 9px 9px;-moz-box-shadow: #B3B3B3 9px 9px 9px; box-shadow: #B3B3B3 9px 9px 9px;padding: 15px;text-align: center;vertical-align: middle;">
  <div id="content" style="position: relative;top: 50%;transform: translateY(-50%); ">
    <span>
      <%=raw @eno_card.text %>
    </span>
  </div>
</div>

app/views/eno_cards/show_random.html.erb
<script type="text/javascript">
  setInterval(function() {
                window.location.reload();
            }, 600000);
            $(document).ready(function() {
                // document.onclick = function() {
                //     location.reload();
                // };
                // document.ontouch = function() {
                //     location.reload();
                // };
                $('#wrapper').click(function() {
                    location.reload();
                });
                $('#content').textfill({
                    maxFontPixels: 100,
                    changeLineHeight: true
                });
            });
</script>
<div id="wrapper" style="overflow:hidden;width:100hh;height:70vh;-webkit-border-radius: 20px;-moz-border-radius: 20px;border-radius: 20px;border:5px solid #000000;background:rgba(226,227,193,0.5);-webkit-box-shadow: #B3B3B3 9px 9px 9px;-moz-box-shadow: #B3B3B3 9px 9px 9px; box-shadow: #B3B3B3 9px 9px 9px;padding: 15px;text-align: center;vertical-align: middle;">
  <div id="content" style="position: relative;top: 50%;transform: translateY(-50%);">
    <span><%=raw @eno_card.text %></span>
  </div>
</div>

app/views/eno_cards/verify.html.erb
loaderio-a6c8a368ec0ac4c24c199b8d6cf9aca1

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brian Eno's Oblique Strategies</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MC41WFQNK1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-MC41WFQNK1');
    </script>
  </head>
  <body>
    <%= yield %>
    <!--Footer-->
    <div id="footer">
      <h3 class="copyright">Developed by <a href="https://github.com/Skeyelab">Eric Dahl</a> - v<%= Version.current %></h3>
      <h1 class="credit"><a href="https://en.wikipedia.org/wiki/Oblique_Strategies" target="_blank">Brian Eno's Oblique Strategies</a></h3>
      <div style="clear: both"></div>
    </div>
  </body>
</html>